import type { HistoryResponse, RequestResponse } from '../../types/api';

export const demoRequests: RequestResponse[] = [
  {
    id: 8021,
    title: 'API endpoint timeout issue',
    description: 'Requests to the payment status endpoint occasionally time out after 30 seconds during peak traffic.',
    category: 'BUG',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    clientId: 4,
    assignedDeveloperId: 2,
    version: 3,
    createdAt: '2026-07-31T02:15:00Z',
    updatedAt: '2026-08-01T04:42:00Z',
  },
  {
    id: 8022,
    title: 'New dashboard widget: revenue',
    description: 'Add a monthly recurring revenue widget to the operations dashboard.',
    category: 'FEATURE',
    priority: 'MEDIUM',
    status: 'PENDING',
    clientId: 5,
    assignedDeveloperId: null,
    version: 0,
    createdAt: '2026-07-30T08:20:00Z',
    updatedAt: '2026-07-30T08:20:00Z',
  },
  {
    id: 8023,
    title: 'Billing export format question',
    description: 'Can the monthly billing export include both KRW and USD totals?',
    category: 'INQUIRY',
    priority: 'LOW',
    status: 'DONE',
    clientId: 6,
    assignedDeveloperId: 3,
    version: 4,
    createdAt: '2026-07-28T01:10:00Z',
    updatedAt: '2026-07-30T06:11:00Z',
  },
  {
    id: 8024,
    title: 'User role synchronization failing',
    description: 'New client users are not receiving the expected CRM role after nightly synchronization.',
    category: 'BUG',
    priority: 'HIGH',
    status: 'PENDING',
    clientId: 7,
    assignedDeveloperId: 2,
    version: 1,
    createdAt: '2026-07-27T11:45:00Z',
    updatedAt: '2026-07-27T13:12:00Z',
  },
  {
    id: 8025,
    title: 'Add maintenance window notice',
    description: 'Display scheduled maintenance notices on the customer portal login page.',
    category: 'FEATURE',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    clientId: 8,
    assignedDeveloperId: 3,
    version: 2,
    createdAt: '2026-07-25T03:32:00Z',
    updatedAt: '2026-07-29T09:05:00Z',
  },
  {
    id: 8026,
    title: 'Clarify API rate limits',
    description: 'Please confirm the current request-per-minute limit for the public API.',
    category: 'INQUIRY',
    priority: 'LOW',
    status: 'DONE',
    clientId: 4,
    assignedDeveloperId: 2,
    version: 3,
    createdAt: '2026-07-24T05:18:00Z',
    updatedAt: '2026-07-25T07:40:00Z',
  },
];

export const demoHistories: Record<number, HistoryResponse[]> = {
  8021: [
    {
      id: 1,
      requestId: 8021,
      changedBy: 4,
      fromStatus: null,
      toStatus: 'PENDING',
      memo: 'Request created by client.',
      changedAt: '2026-07-31T02:15:00Z',
    },
    {
      id: 2,
      requestId: 8021,
      changedBy: 1,
      fromStatus: 'PENDING',
      toStatus: 'PENDING',
      memo: 'Assigned to developer #2.',
      changedAt: '2026-07-31T03:05:00Z',
    },
    {
      id: 3,
      requestId: 8021,
      changedBy: 2,
      fromStatus: 'PENDING',
      toStatus: 'IN_PROGRESS',
      memo: 'Started investigating timeout traces.',
      changedAt: '2026-08-01T04:42:00Z',
    },
  ],
};
